// Generated by scripts/scan-symps-assets.mjs — do not edit by hand.
export type ProductPhoto = {src: string; w: number; h: number};
export const PRODUCT_IMAGES: Record<string, ProductPhoto> = {
	"opaline": {
		"src": "symps/products/opaline.png",
		"w": 1277,
		"h": 4261
	}
};
export const PROJECT_IMAGES: string[] = [];
