import type {MachineSpec} from './kit/Machine3D';

/**
 * 3D specifications of each machine.
 *
 * Opaline is modelled from photographs of the real machine.
 * The others are modelled from the machines visible in the Symp's showroom
 * photos (colours, rails, cabinets, wheels) and still need to be checked
 * against each real product.
 */
export const SPECS: Record<string, MachineSpec> = {
	opaline: {
		id: 'opaline',
		body: '#1E3C9E',
		accent: '#C0182D',
		rail: 'black',
		rails: 2,
		mast: 2.75,
		tower: {w: 0.38, h: 0.92, d: 0.34},
		steelStrip: true,
		controlPanel: 'red',
		plate: 'OPALINE',
		sympsPlate: true,
		wheel: 'alloy',
		wheelR: 0.1,
		chassisSize: [0.5, 0.74],
		screen: true,
	},
	m1: {
		id: 'm1',
		body: '#16171A',
		accent: '#2A2B30',
		rail: 'black',
		rails: 2,
		mast: 2.6,
		tower: {w: 0.3, h: 0.42, d: 0.3},
		controlPanel: 'black',
		sympsPlate: true,
		wheel: 'black',
		wheelR: 0.075,
		chassisSize: [0.5, 0.7],
		screen: true,
	},
	graphite: {
		id: 'graphite',
		body: '#4A4D53',
		accent: '#2F3135',
		rail: 'silver',
		rails: 3,
		mast: 2.55,
		tower: {w: 0.32, h: 0.34, d: 0.3},
		wheel: 'alloy',
		wheelR: 0.085,
		chassisSize: [0.5, 0.72],
		screen: true,
		fan: true,
	},
	'black-2': {
		id: 'black-2',
		body: '#111214',
		accent: '#B3122C',
		rail: 'black',
		rails: 2,
		mast: 2.8,
		tower: {w: 0.4, h: 1.0, d: 0.36},
		controlPanel: 'black',
		swoosh: '#B3122C',
		sympsPlate: true,
		wheel: 'black',
		wheelR: 0.085,
		chassisSize: [0.52, 0.76],
		screen: true,
	},
	white: {
		id: 'white',
		body: '#ECECE8',
		accent: '#C0182D',
		rail: 'silver',
		rails: 1,
		mast: 2.5,
		tower: {w: 0.28, h: 0.3, d: 0.26},
		controlPanel: 'red',
		wheel: 'black',
		wheelR: 0.07,
		chassisSize: [0.44, 0.62],
		screen: true,
	},
	t1000: {
		id: 't1000',
		body: '#2A2C30',
		accent: '#C0182D',
		rail: 'silver',
		rails: 3,
		mast: 3.1,
		tower: {w: 0.42, h: 0.8, d: 0.38},
		controlPanel: 'red',
		sympsPlate: true,
		wheel: 'alloy',
		wheelR: 0.1,
		chassisSize: [0.6, 0.86],
		screen: true,
		fan: true,
	},
	access: {
		id: 'access',
		body: '#8E959D',
		accent: '#2F3135',
		rail: 'black',
		rails: 1,
		mast: 2.3,
		tower: null,
		wheel: 'black',
		wheelR: 0.07,
		chassisSize: [0.42, 0.6],
	},
	ruby: {
		id: 'ruby',
		body: '#141416',
		chassis: '#9E1228',
		cabinet: '#9E1228',
		accent: '#9E1228',
		rail: 'black',
		rails: 2,
		mast: 2.7,
		tower: {w: 0.34, h: 0.62, d: 0.32},
		controlPanel: 'black',
		sympsPlate: true,
		mastPlates: '#9E1228',
		wheel: 'black',
		wheelR: 0.08,
		chassisSize: [0.52, 0.74],
		screen: true,
	},
};
